### PR TITLE
new features

### PR DESCRIPTION
**Pull request by Zecat**
#### enhancements
- input still focus when we navigate with arrows in the result list, using iron-selector insead of IronMenuBehavior
- put the typeahead logic in IronTypeaheadBehavior
- bind paper-input attributes
- provide methods to control the results manually
- I used hidden$="[[_hideResults]]" instead of dom-if -> is it better ?
- various var name change, fixes & enhancements
#### bugs
- moving up/down in the results with arrow should not change input caret position, need to prevent default  input's comportement.
- The default filterFn function should pay attention to exclude regExp characters in "value" so they are not interpreted.
- mousedown on a result should not focus it
- tap outside the element should close the results layer but for now, because result are focused on tap, we can't just use blur handler on paper-input

### CODE REVIEW

**Comment by Zecat** [comment]
Why don't you like these new lines ? It avoids the headache, I was trying to have the same syntaxe as officials elements, it's as you want :) About the behavior, I thought it was important to separate the logic from the visual, I think the sooner the better because there is still plenty possibility on both side. I start write paper-typeahead-perform element then I turned it in a behavior because this is a good feature. For the same result, no need to give an id to paper-typeahead-perform to access it, attributes and methods are at the root element. That's just my opinion, also maybe it should be called "paper-typeahead-behavior".

**Comment by Zecat** [comment]
I think it's just unclear when to use or not dom-if, I put it back, using IronSelectableBehavior this makes things easier, no strange access to dynamically created node anymore.

**Comment by samccone** [comment]
> I think it's just unclear when to use or not dom-if, I put it back, using IronSelectableBehavior this makes things easier, no strange access to dynamically created node anymore.

SGTM

**Comment by Zecat** [comment]
I did'nt mean the logic from the visual but the logic of generate the filteredItems vs display and select the filtredItems, but you're right. It's not a typeahead-behavior but more like a array-filter-behavior. About that,  could we just use the filtering feature of the dom-repeat ?

**Comment by Zecat** [comment]
The last two commits are cool, paper-input is part of the selectable array and hover an item select it so the keyboard navigation continue at this point.

**Comment by samccone** [comment]
:bow: great work here @Zecat all merged!!! really really good stuff

**Pull request merged**
